- name: Head node setup
  tags: head_node
  hosts:
    - ss-00
  become: true
  roles:
    - network
    - nfs_common
    - nfs_master
    - slurm_common
    - slurm_master
    - jupyterhub_common
    - jupyterhub_master
    - users_master
  vars_files:
    - ./vars/common.yml

- name: Compute nodes setup
  tags: compute_nodes
  hosts: 
    - ss-01
  become: true
  roles:
    - network
    - nfs_common
    - nfs_slave
    - slurm_common
    - slurm_slave
    - jupyterhub_common
    - jupyterhub_slave
    - users_slave
    - docker
  vars_files:
    - ./vars/common.yml
