- name: Setting up master node
  tags: head_node
  hosts:
    - ss-00
  user: aa_vivas
  become: true
  roles:
    - network
    - nfs_common
    - nfs_master
    - slurm_common
    - slurm_master
    - jupyterhub_common
    - jupyterhub_master
    - users_master
  vars_files:
    - ./vars/common.yml

- name: Setting up slave nodes
  tags: compute_nodes
  hosts: 
    - ss-01
  user: aavivas
  become: true
  roles:
    - network
    - nfs_common
    - nfs_slave
    - slurm_common
    - slurm_slave
    - jupyterhub_common
    - jupyterhub_slave
    - users_slave
  vars_files:
    - ./vars/common.yml
