
- name: Create users in slaves
  user:
    name: "{{ item }}"
    password: "{{ users_passwd | password_hash('sha512') }}"
    shell: /bin/bash 
    system: no             
    createhome: no        
    home: /home/{{ item }}
    groups: slurm,docker
    state: "{{ users_state }}"
  with_sequence: start={{ users_seq_start }} end={{ users_seq_end }} format={{ users_seq_format }}
  tags: users