- name: Create /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
  template:
    src: jupyterhub_config.py.j2
    dest: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
    mode: 0755

- name: Install configurable-http-proxy
  command: npm install -g configurable-http-proxy@4.6.3

- name: Ensure '/opt/jupyterhub/etc/systemd' dir exists
  file: 
    path: /opt/jupyterhub/etc/systemd
    recurse: true
    state: directory

- name: Create jupyterhub.service
  template:
    src: jupyterhub.service.j2
    dest: /opt/jupyterhub/etc/systemd/jupyterhub.service
    mode: 0755

- name: Install /opt/jupyterhub/etc/systemd/jupyterhub.service
  file: 
    src: /opt/jupyterhub/etc/systemd/jupyterhub.service
    dest: /etc/systemd/system/jupyterhub.service
    state: link

- name: Make sure JupyterHub service unit is running
  service:
    state: started
    name: jupyterhub.service

- name: Backup original page.html
  copy:
    src: /opt/jupyterhub/share/jupyterhub/templates/page.html
    dest: /opt/jupyterhub/share/jupyterhub/templates/page.html.back
    remote_src: yes
    backup: no
    force: yes

- name: Deploy custom page.html
  copy:
    src: files/page.html        # from your Ansible "files/" directory
    dest: /opt/jupyterhub/share/jupyterhub/templates/page.html
    owner: root
    group: root
    mode: '0644'
    backup: yes                 # keep a copy of the replaced version

- name: Deploy custom logo
  copy:
    src: files/logo-disc.webp   # from your Ansible "files/" directory
    dest: /opt/jupyterhub/share/jupyterhub/static/images/logo-disc.webp
    owner: root
    group: root
    mode: '0644'
    backup: yes
