- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
  - hostname

- name: Update /etc/hosts
  shell: "grep -qxF \"{{ item.ip }} {{ item.name }}\" /etc/hosts | echo \"{{ item.ip }} {{ item.name }}\" >> /etc/hosts "
  with_items: "{{ cluster_hostnames }}"
  register: cmdln
  check_mode: no
  tags:
  - hostname

- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: present
  tags:
    - firewall

- name: Enabling communication between nodes through the firewall
  shell: "firewall-cmd --zone=trusted --add-source={{ item.ip }} --permanent"
  with_items: "{{ cluster_hostnames }}"
  register: cmdln
  check_mode: no
  tags:
  - firewall

- name: Reload the firewall
  shell: "firewall-cmd --reload"
  register: cmdln
  check_mode: no
  tags:
  - firewall

- name: Update ubuntu
  apt: update_cache=yes

- name: Enabling HTTP through the firewall
  shell: "firewall-cmd --zone=public --add-service http"
  register: cmdln
  check_mode: no
  tags:
  - firewall

- name: Enabling HTTPS through the firewall
  shell: "firewall-cmd --zone=public --add-service https"
  register: cmdln
  check_mode: no
  tags:
  - firewall
