- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
  - hostname

- name: Ensure ufw is installed
  package:
    name: ufw
    state: present
  tags:
    - firewall

- name: Enable ufw
  ufw:
    state: enabled
  tags:
    - firewall

- name: Allow communication between cluster nodes
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item].ansible_host }}"
  loop: "{{ groups['cluster'] }}"
  when: hostvars[item].ansible_host is defined
  tags:
    - firewall

- name: Allow HTTP through the firewall
  ufw:
    rule: allow
    port: "8000"
    proto: tcp
  tags:
    - firewall

# - name: Allow HTTPS through the firewall
#   ufw:
#     rule: allow
#     port: "443"
#     proto: tcp
#   tags:
#     - firewall