- name: Install prerequisites
  apt:
    name:
      - curl
      - gnupg
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: yes

- name: Install Docker (using get.docker.com script)
  shell: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
