- name: Update ubuntu
  apt: update_cache=yes

- name: Python requirements
  apt:
    pkg:
      - build-essential
      - libssl-dev 
      - libffi-dev 
      - python3.10-dev
      - python3.10-venv
    state: present

- name: Create virtualenv in /opt/jupyterhub/
  command: python3 -m venv /opt/jupyterhub/

- name: Ensure '/opt/jupyterhub/etc/jupyterhub/' dir exists
  file: 
    path: /opt/jupyterhub/etc/jupyterhub/
    recurse: true
    state: directory

- name: Install JupyterHub/JuppyterLab
  command: |
    /opt/jupyterhub/bin/pip3.10 install \
      wheel \
      jupyterhub==4.1.5 \
      jupyterlab \
      ipywidgets \
      batchspawner

- name: Ensure symlinks for JupyterHub/Lab executables in /usr/local/bin
  file:
    src: "/opt/jupyterhub/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: yes
  loop:
    - jupyterhub-singleuser
    - batchspawner-singleuser
  tags:
    - jupyterhub_symlinks
