- name: Update ubuntu
  apt: update_cache=yes

- name: Python tutorial system requirements
  apt:
    pkg:
      - build-essential
      - libssl-dev 
      - libffi-dev 
      - python3-dev
      - python3.10-venv
      - python3.10-passlib
    state: present

- name: Create virtualenv in /opt/jupyterhub/
  command: python3 -m venv /opt/jupyterhub/

- name: Ensure '/opt/jupyterhub/etc/jupyterhub/' dir exists
  file: 
    path: /opt/jupyterhub/etc/jupyterhub/
    recurse: true
    state: directory
